## Import Liberaries

In [1]:
import numpy as np 
import pandas as pd 

from sklearn.preprocessing import StandardScaler

## Pre-Processing

### Load data

In [4]:
import os

BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))

train_path = os.path.join(BASE_DIR, 'dataSets', 'train.csv')
test_path = os.path.join(BASE_DIR, 'dataSets', 'test.csv')

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [6]:
x_train = train.drop(['id', 'Irrigation_Need'], axis=1)
y_train = train['Irrigation_Need']

x_test = test.drop('id', axis=1)

print(f"Training data: {x_train.shape[0]} samples, {x_train.shape[1]} features")
print(f"Test data: {x_test.shape[0]} samples, {x_test.shape[1]} features")

Training data: 630000 samples, 19 features
Test data: 270000 samples, 19 features

In [7]:
x_train.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South

In [8]:
x_train.describe()

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,6.482497,37.304482,0.922858,1.744605,26.998166,61.563180,1462.207566,7.513382,10.375394,7.517745,62.318177
std,0.922504,16.377082,0.365808,0.952321,8.623621,19.708152,612.989738,1.999322,5.689458,4.218124,34.246939
min,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,5.690000,23.340000,0.610000,0.930000,19.517500,45.390000,954.570000,5.760000,5.280000,3.880000,33.140000
50%,6.440000,37.750000,0.910000,1.740000,26.960000,61.650000,1467.160000,7.580000,10.480000,7.380000,61.150000
75%,7.270000,51.270000,1.220000,2.580000,34.540000,79.120000,2054.280000,9.250000,15.430000,11.140000,92.690000
max,8.200000,64.990000,1.600000,3.500000,42.000000,94.990000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [9]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 19 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Soil_Type                630000 non-null  object
 1   Soil_pH                  630000 non-null  float64
 2   Soil_Moisture            630000 non-null  float64
 3   Organic_Carbon           630000 non-null  float64
 4   Electrical_Conductivity  630000 non-null  float64
 5   Temperature_C            630000 non-null  float64
 6   Humidity                 630000 non-null  float64
 7   Rainfall_mm              630000 non-null  float64
 8   Sunlight_Hours           630000 non-null  float64
 9   Wind_Speed_kmh           630000 non-null  float64
 10  Crop_Type                630000 non-null  object
 11  Crop_Growth_Stage        630000 non-null  object
 12  Season                   630000 non-null  object
 13  Irrigation_Type          630000 non-null  object
 14  Water_Source             630000 non-null  object
 15  Field_Area_hectare       630000 non-null  float64
 16  Mulching_Used            630000 non-null  object
 17  Previous_Irrigation_mm   630000 non-null  float64
 18  Region                   630000 non-null  object
dtypes: float64(11), object(8)
memory usage: 91.3+ MB

In [10]:
x_train.isnull().sum()

Soil_Type                  0
Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
Crop_Type                  0
Crop_Growth_Stage          0
Season                     0
Irrigation_Type            0
Water_Source               0
Field_Area_hectare         0
Mulching_Used              0
Previous_Irrigation_mm     0
Region                     0
dtype: int64

In [11]:
x_test.isnull().sum()

Soil_Type                  0
Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
Crop_Type                  0
Crop_Growth_Stage          0
Season                     0
Irrigation_Type            0
Water_Source               0
Field_Area_hectare         0
Mulching_Used              0
Previous_Irrigation_mm     0
Region                     0
dtype: int64

In [12]:
print(x_train.duplicated().sum())
print(x_test.duplicated().sum())

0
0

In [13]:
x_train.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South

### Encoding

In [14]:
cat_v= ['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season', 'Irrigation_Type',
        'Water_Source', 'Mulching_Used', 'Region']

num_v= (x_train.drop(columns=cat_v).columns).tolist()

for i in cat_v:
               print(f"{i}: {x_train[i].unique()}")

Soil_Type: ['Loamy' 'Clay' 'Sandy' 'Silt']
Crop_Type: ['Sugarcane' 'Wheat' 'Rice' 'Potato' 'Cotton' 'Maize']
Crop_Growth_Stage: ['Sowing' 'Vegetative' 'Flowering' 'Harvest']
Season: ['Zaid' 'Kharif' 'Rabi']
Irrigation_Type: ['Drip' 'Rainfed' 'Sprinkler' 'Canal']
Water_Source: ['Rainwater' 'River' 'Reservoir' 'Groundwater']
Mulching_Used: ['No' 'Yes']
Region: ['East' 'South' 'North' 'West' 'Central']

In [50]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [15]:
def safe_one_hot_encode(x_train, x_test, columns):

    for column_name in columns:

        if column_name in x_train.columns:

            train_dummies = pd.get_dummies(x_train[column_name], prefix=column_name)
            test_dummies = pd.get_dummies(x_test[column_name], prefix=column_name)


            x_train = x_train.drop(column_name, axis=1)
            x_test = x_test.drop(column_name, axis=1)

            x_train = pd.concat([x_train, train_dummies], axis=1)
            x_test = pd.concat([x_test, test_dummies], axis=1)

    x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)

    return x_train, x_test

x_train_encoded, x_test_encoded = safe_one_hot_encode(x_train, x_test, cat_v)

x_train_encoded

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,...,Water_Source_Rainwater,Water_Source_Reservoir,Water_Source_River,Mulching_Used_No,Mulching_Used_Yes,Region_Central,Region_East,Region_North,Region_South,Region_West
0,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,0.82,...,True,False,False,True,False,False,True,False,False,False
1,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,5.27,...,False,False,True,False,True,False,False,False,True,False
2,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,8.24,...,False,True,False,False,True,False,False,True,False,False
3,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,8.32,...,False,False,True,False,True,False,False,False,True,False
4,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,7.37,...,False,False,True,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,4.35,...,False,False,True,True,False,False,False,False,True,False
629996,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,12.97,...,False,False,False,False,True,True,False,False,False,False
629997,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25,13.58,...,False,True,False,False,True,False,False,False,True,False
629998,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,0.79,...,False,False,False,False,True,False,True,False,False,False
629999,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,3.80,...,False,True,False,True,False,False,False,False,False,True

In [16]:
x_test_encoded

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,...,Water_Source_Rainwater,Water_Source_Reservoir,Water_Source_River,Mulching_Used_No,Mulching_Used_Yes,Region_Central,Region_East,Region_North,Region_South,Region_West
0,6.36,26.19,0.59,2.81,17.83,30.24,1533.38,5.40,3.00,13.59,...,False,False,True,False,True,False,False,False,False,True
1,5.87,9.88,1.18,3.26,21.18,78.07,576.05,7.22,15.88,6.12,...,False,True,False,False,True,False,False,False,True,False
2,6.22,26.55,0.96,0.85,26.87,60.35,545.30,9.43,2.63,3.11,...,False,True,False,False,True,False,True,False,False,False
3,7.68,53.58,0.83,0.55,41.74,36.05,1211.03,6.69,1.86,2.27,...,False,False,False,True,False,False,False,True,False,False
4,5.23,59.02,0.54,2.11,41.08,52.47,1321.91,4.11,5.71,12.39,...,False,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269995,5.63,51.90,0.68,2.58,33.27,72.09,2326.61,7.09,10.02,2.93,...,False,False,True,False,True,False,True,False,False,False
269996,7.84,45.16,0.85,1.04,27.55,45.16,2322.37,5.15,5.62,11.23,...,False,False,False,False,True,False,False,False,False,True
269997,7.83,11.02,1.56,1.90,23.39,64.87,996.72,10.44,9.98,2.88,...,False,False,False,False,True,False,True,False,False,False
269998,7.12,10.18,1.32,2.65,41.09,58.04,1130.71,5.11,1.46,5.71,...,False,False,True,False,True,False,True,False,False,False
269999,6.61,24.96,1.41,3.41,35.15,61.30,1270.60,9.69,9.93,4.01,...,False,True,False,True,False,False,False,False,True,False

### Remove outliers

In [17]:
def cap_outliers_percentile(x_train, x_test, lower_percentile=10, upper_percentile=90):

    print("\n" + "="*50)
    print("CAPPING OUTLIERS (Winsorization)")
    print(f"Bounds derived from Train: {lower_percentile}th - {upper_percentile}th percentiles")
    print("="*50)

    x_train_capped = x_train.copy()
    x_test_capped = x_test.copy()

    # loop over columns instead of numpy indexing
    for col in x_train.columns:

        # skip non-numeric columns
        if x_train[col].dtype not in [np.int64, np.float64]:
            continue

        # compute bounds from TRAIN only
        lower_bound = np.percentile(x_train[col], lower_percentile)
        upper_bound = np.percentile(x_train[col], upper_percentile)

        # apply clipping
        x_train_capped[col] = np.clip(x_train[col], lower_bound, upper_bound)
        x_test_capped[col] = np.clip(x_test[col], lower_bound, upper_bound)

    return x_train_capped, x_test_capped
x_train, x_test = cap_outliers_percentile(x_train_encoded, x_test_encoded)


print(f"Shape of training: {x_train.shape}")
print(f"Shape of testing: {x_test.shape}")

==================================================
CAPPING OUTLIERS (Winsorization)
Bounds derived from Train: 10th - 90th percentiles
==================================================
Shape of training: (630000, 43)
Shape of testing: (270000, 43)

### Correlation

In [18]:
def check_correlation(df, threshold=0.8):

    num_df = df.select_dtypes(include=['bool', 'float64'])

    corr_matrix = num_df.corr()

    high_corr_pairs = []
    cols = num_df.columns

    n_features = len(cols)

    for i in range(n_features):
        for j in range(i + 1, n_features):

            corr_value = corr_matrix.iloc[i, j]

            if abs(corr_value) > threshold:
                high_corr_pairs.append((cols[i], cols[j], corr_value))

    if len(high_corr_pairs) == 0:
        print(f"No high correlations found (threshold={threshold})")
        print("No significant multicollinearity detected")

    else:
        print(f"Found {len(high_corr_pairs)} feature pairs with correlation > {threshold}")

        for i, j, corr in high_corr_pairs[:20]:
            print(f"  - {i} & {j}: {corr:.3f}")

    return corr_matrix


corr_matrix = check_correlation(x_train, threshold=0.8)

Found 1 feature pairs with correlation > 0.8
  - Mulching_Used_No & Mulching_Used_Yes: -1.000

In [19]:
x_train= x_train.drop(columns= 'Mulching_Used_No')
x_test= x_test.drop(columns= 'Mulching_Used_No')
x_train

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,...,Water_Source_Groundwater,Water_Source_Rainwater,Water_Source_Reservoir,Water_Source_River,Mulching_Used_Yes,Region_Central,Region_East,Region_North,Region_South,Region_West
0,5.23,32.58,1.01,3.05,15.14,50.61,725.99,5.90,16.79,1.73,...,False,True,False,False,False,False,True,False,False,False
1,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,5.27,...,False,False,False,True,True,False,False,False,True,False
2,5.69,27.71,0.81,2.83,26.97,87.77,2201.70,6.05,3.85,8.24,...,False,False,True,False,True,False,False,True,False,False
3,5.65,14.01,1.33,0.87,15.14,61.57,1357.33,9.12,2.48,8.32,...,False,False,False,True,True,False,False,False,True,False
4,7.78,59.14,0.43,0.96,20.22,87.77,1538.20,6.95,13.94,7.37,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,6.54,14.01,1.15,1.86,26.65,33.52,1041.33,10.24,18.21,4.35,...,False,False,False,True,False,False,False,False,True,False
629996,7.03,54.49,0.96,2.35,36.99,87.77,1419.57,9.93,17.99,12.97,...,True,False,False,False,True,True,False,False,False,False
629997,6.52,14.01,0.93,0.45,37.82,70.98,643.77,8.19,17.25,13.45,...,False,False,True,False,True,False,False,False,True,False
629998,5.93,42.86,0.43,3.07,34.99,87.77,2298.21,9.88,5.00,1.73,...,True,False,False,False,True,False,True,False,False,False
629999,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,3.80,...,False,False,True,False,False,False,False,False,False,True

### Z-Score

In [ ]:
# x_train.to_csv("processed_x_train.csv", index=False)
# x_test.to_csv("processed_x_test.csv", index=False)

In [20]:
scaler = StandardScaler()
def z_scoring(x_train, x_test):
               x_train_scaled = pd.DataFrame(
               scaler.fit_transform(x_train),
               columns=x_train.columns,
               index=x_train.index)

               x_test_scaled = pd.DataFrame(
               scaler.transform(x_test),
               columns=x_test.columns,
               index=x_test.index)

               train_mean = x_train_scaled.to_numpy().mean()
               train_std = x_train_scaled.to_numpy().std()

               test_mean = x_test_scaled.to_numpy().mean()
               test_std = x_test_scaled.to_numpy().std()

               print(f"Train mean ≈ {train_mean:.6f}, std ≈ {train_std:.6f}")
               print(f"Test mean ≈ {test_mean:.6f}, std ≈ {test_std:.6f}")
               return x_train_scaled, x_test_scaled
x_train_scaled, x_test_scaled= z_scoring(x_train, x_test)

Train mean ≈ -0.000000, std ≈ 1.000000
Test mean ≈ -0.000112, std ≈ 0.999937

In [21]:
x_train

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,...,Water_Source_Groundwater,Water_Source_Rainwater,Water_Source_Reservoir,Water_Source_River,Mulching_Used_Yes,Region_Central,Region_East,Region_North,Region_South,Region_West
0,5.23,32.58,1.01,3.05,15.14,50.61,725.99,5.90,16.79,1.73,...,False,True,False,False,False,False,True,False,False,False
1,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,5.27,...,False,False,False,True,True,False,False,False,True,False
2,5.69,27.71,0.81,2.83,26.97,87.77,2201.70,6.05,3.85,8.24,...,False,False,True,False,True,False,False,True,False,False
3,5.65,14.01,1.33,0.87,15.14,61.57,1357.33,9.12,2.48,8.32,...,False,False,False,True,True,False,False,False,True,False
4,7.78,59.14,0.43,0.96,20.22,87.77,1538.20,6.95,13.94,7.37,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,6.54,14.01,1.15,1.86,26.65,33.52,1041.33,10.24,18.21,4.35,...,False,False,False,True,False,False,False,False,True,False
629996,7.03,54.49,0.96,2.35,36.99,87.77,1419.57,9.93,17.99,12.97,...,True,False,False,False,True,True,False,False,False,False
629997,6.52,14.01,0.93,0.45,37.82,70.98,643.77,8.19,17.25,13.45,...,False,False,True,False,True,False,False,False,True,False
629998,5.93,42.86,0.43,3.07,34.99,87.77,2298.21,9.88,5.00,1.73,...,True,False,False,False,True,False,True,False,False,False
629999,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,3.80,...,False,False,True,False,False,False,False,False,False,True

In [22]:
x_train_scaled

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,...,Water_Source_Groundwater,Water_Source_Rainwater,Water_Source_Reservoir,Water_Source_River,Mulching_Used_Yes,Region_Central,Region_East,Region_North,Region_South,Region_West
0,-1.442661,-0.305825,0.255108,1.467669,-1.456928,-0.595073,-1.327550,-0.854247,1.183678,-1.450655,...,-0.569175,1.765442,-0.590778,-0.583018,-0.995398,-0.494319,1.998384,-0.470352,-0.521763,-0.512839
1,0.687663,1.247443,-1.393582,0.290396,-0.502676,0.337200,-0.865814,-0.282718,-1.291525,-0.562385,...,-0.569175,-0.566430,-0.590778,1.715214,1.004623,-0.494319,-0.500404,-0.470352,1.916580,-0.512839
2,-0.912959,-0.620615,-0.323379,1.221002,-0.005925,1.413232,1.296505,-0.774868,-1.206556,0.182858,...,-0.569175,-0.566430,1.692682,-0.583018,1.004623,-0.494319,-0.500404,2.126068,-0.521763,-0.512839
3,-0.959020,-1.506165,1.180689,-0.976573,-1.456928,-0.002742,-0.204924,0.849758,-1.459617,0.202932,...,-0.569175,-0.566430,-0.590778,1.715214,1.004623,-0.494319,-0.500404,-0.470352,1.916580,-0.512839
4,1.493732,1.410978,-1.422506,-0.875664,-0.833843,1.413232,0.116693,-0.298594,0.657235,-0.035445,...,-0.569175,-0.566430,-0.590778,1.715214,-0.995398,-0.494319,-0.500404,-0.470352,1.916580,-0.512839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,0.065839,-1.506165,0.660050,0.133427,-0.045175,-1.518699,-0.766824,1.442455,1.445975,-0.793235,...,-0.569175,-0.566430,-0.590778,1.715214,-0.995398,-0.494319,-0.500404,-0.470352,1.916580,-0.512839
629996,0.630087,1.110409,0.110486,0.682820,1.223073,1.413232,-0.094251,1.278405,1.405337,1.369727,...,1.756928,-0.566430,-0.590778,-0.583018,1.004623,2.022986,-0.500404,-0.470352,-0.521763,-0.512839
629997,0.042808,-1.506165,0.023713,-1.447482,1.324876,0.505820,-1.473751,0.357607,1.268647,1.490170,...,-0.569175,-0.566430,1.692682,-0.583018,1.004623,-0.494319,-0.500404,-0.470352,1.916580,-0.512839
629998,-0.636592,0.358661,-1.422506,1.490093,0.977764,1.413232,1.468116,1.251945,-0.994132,-1.450655,...,1.756928,-0.566430,-0.590778,-0.583018,1.004623,-0.494319,1.998384,-0.470352,-0.521763,-0.512839
629999,0.618572,-0.126129,0.775747,-1.436270,-0.012058,0.146422,-0.361011,0.209433,-1.415285,-0.931243,...,-0.569175,-0.566430,1.692682,-0.583018,-0.995398,-0.494319,-0.500404,-0.470352,-0.521763,1.949931

## Models

In [31]:
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier

logistic Regression From Scratch

In [54]:
class LogisticRegressionScratch:
    def __init__(self, lr=0.01, n_iters=1000):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None
        self.classes_ = None

    def softmax(self, z):
        z_shifted = z - np.max(z, axis=1, keepdims=True)
        exp_z = np.exp(z_shifted)
        return exp_z / np.sum(exp_z, axis=1, keepdims=True)

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)

        self.classes_ = np.unique(y)
        n_classes = len(self.classes_)
        label_map = {c: idx for idx, c in enumerate(self.classes_)}
        y_mapped = np.array([label_map[c] for c in y])

        n_samples, n_features = X.shape
        self.weights = np.zeros((n_features, n_classes))
        self.bias = np.zeros(n_classes)

        # one-hot encode y
        y_onehot = np.zeros((n_samples, n_classes))
        y_onehot[np.arange(n_samples), y_mapped] = 1

        for i in range(self.n_iters):
            linear_model = np.dot(X, self.weights) + self.bias
            y_pred = self.softmax(linear_model)

            error = y_pred - y_onehot
            dw = (1 / n_samples) * np.dot(X.T, error)
            db = (1 / n_samples) * np.sum(error, axis=0)

            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        X = np.array(X)
        linear_model = np.dot(X, self.weights) + self.bias
        y_pred = self.softmax(linear_model)
        return self.classes_[np.argmax(y_pred, axis=1)]

In [55]:
model = LogisticRegressionScratch(lr=0.01, n_iters=1000)

model.fit(x_train_scaled, y_train)

preds = model.predict(x_test_scaled)

In [57]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_train, model.predict(x_train_scaled))
print("Train Accuracy:", accuracy)

Train Accuracy: 0.8598079365079365

In [41]:
models = {
    'LightGBM': lgb.LGBMClassifier(),
    'XGBoost': xgb.XGBClassifier(),
    'CatBoost': CatBoostClassifier(),
    'ExtraTrees': ExtraTreesClassifier(),
    'RandomForest': RandomForestClassifier()
}

LightGBM - Fast gradient boosting

In [33]:
def train_lightgbm(X_train, y_train, X_val, y_val):
    model = lgb.LGBMClassifier(
        n_estimators=2000,
        learning_rate=0.03,
        max_depth=8,
        num_leaves=63,
        min_child_samples=20,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=0.1,
        random_state=42,
        n_jobs=-1,
        class_weight='balanced'
    )
    
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(50, verbose=False)]
    )
    
    return model

XGBoost - Extreme gradient boosting

In [34]:
def train_xgboost(X_train, y_train, X_val, y_val):
    model = xgb.XGBClassifier(
        n_estimators=2000,
        learning_rate=0.03,
        max_depth=8,
        min_child_weight=3,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        random_state=42,
        eval_metric='mlogloss',
        n_jobs=-1,
        tree_method='hist'
    )
    
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )
    
    return model

CatBoost - Categorical-aware boosting

In [35]:
def train_catboost(X_train, y_train, X_val, y_val):
    model = CatBoostClassifier(
        iterations=2000,
        learning_rate=0.03,
        depth=8,
        l2_leaf_reg=3,
        random_seed=42,
        verbose=0,
        auto_class_weights='Balanced',
        eval_metric='TotalF1'
    )
    
    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50
    )
    
    return model

ExtraTrees - Extremely randomized trees

In [36]:
def train_extratrees(X_train, y_train):
    model = ExtraTreesClassifier(
        n_estimators=1000,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1,
        class_weight='balanced'
    )
    
    model.fit(X_train, y_train)
    return model


RandomForest - Classic ensemble

In [37]:
def train_randomforest(X_train, y_train):
    model = RandomForestClassifier(
        n_estimators=1000,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1,
        class_weight='balanced'
    )
    
    model.fit(X_train, y_train)
    return model

In [38]:
def train_sklearn_model(model, X_train, y_train):
    model.fit(X_train, y_train)
    return model

In [39]:
def train_model(name, model, X_tr, y_tr, X_val, y_val):
    
    if name == 'LightGBM':
        return train_lightgbm(X_tr, y_tr, X_val, y_val)
    
    elif name == 'XGBoost':
        return train_xgboost(X_tr, y_tr, X_val, y_val)
    
    elif name == 'CatBoost':
        return train_catboost(X_tr, y_tr, X_val, y_val)
    
    elif name == 'ExtraTrees':
        return train_extratrees(X_tr, y_tr)
    
    elif name == 'RandomForest':
        return train_randomforest(X_tr, y_tr)
    
    else:
        raise ValueError(f"Unknown model: {name}")

In [43]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [47]:
for name, model in models.items():
    print(f"\nTraining {name}")
    
    for fold, (train_idx, val_idx) in enumerate(skf.split(x_train, y_train)):
        
        X_tr = x_train.iloc[train_idx]
        y_tr = y_train[train_idx]
        X_val = x_train.iloc[val_idx]
        y_val = y_train[val_idx]
        
        model_fold = train_model(name, model, X_tr, y_tr, X_val, y_val)
        
        preds = model_fold.predict(X_val)

Training LightGBM
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.043068 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2626
[LightGBM] [Info] Number of data points in the train set: 504000, number of used features: 42
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -1.098612

KeyboardInterrupt: